### PR TITLE
Fix deprecation warnings

### PR DESCRIPTION
**Pull request by AJenbo**
If all a function does it forward the call to the parent then there isn't actually a need to implement it, since methods are inherited.

After this change the action is able to progress to the PHPStan portion and report on the detected level 0 issues. I fixed about 1/3 of the issues but there are still 44 left. Good luck.

### CODE REVIEW

**Comment by condor2** [comment]
Tks.

**Comment by condor2** [comment]
@AJenbo When you have time can you help me to fix the remaining 12 warnings?

Tks

**Comment by AJenbo** [comment]
K, but you have to test and fix any issues with it your self. I don't have time for that part.
https://github.com/condor2/Opencart_23xx/pull/26

**Comment by condor2** [comment]
OK. Tks for help.

**Pull request merged**
